import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Wesley v.d. Burgt CV",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex flex-col h-screen bg-gray-900 text-white">
                    <Navbar />
                    <main className="flex-1 overflow-y-auto">
                        <div className="container mx-auto px-4 py-12">
                            {children}
                        </div>
                    </main>
                </div>
            </body>
        </html>
    );
}

