import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Wesley v.d. Burgt CV",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
                <div className="flex flex-col min-h-screen bg-gray-900 text-white">
                    <div className="fixed top-0 left-0 w-full z-3">
                        <Navbar />
                    </div>

                    <main className="flex-1">
                        <div className="container mx-auto px-4 pt-20 pb-4">
                            {children}
                        </div>
                    </main>

                    <footer className="w-full bg-black text-center pt-1 pb-2">
                        <a href="mailto:wesleyburgt@gmail.com" className="p-1">
                            contact me at: wesleyburgt@gmail.com
                        </a>
                    </footer>
                </div>
            </body>
        </html>
    );
}

